# Generated by Django 4.0.6 on 2022-08-02 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidhaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidhaa_jina', models.CharField(max_length=264)),
                ('bidhaa_shipping_cost', models.IntegerField()),
                ('bidhaa_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('bidhaa_country', models.CharField(max_length=264)),
                ('bidhaa_shipping_days', models.IntegerField()),
            ],
        ),
    ]
